### ISSUE TITLE
Consider optimize `apache-shardingsphere-operator-charts` for better usability

### ISSUE THREAD

**Issue by mlycore** [apache/shardingsphere-on-cloud#115]
TODO

**Comment by xuanyuan300** [comment]
Refered to the installation of [StreamNative](https://docs.streamnative.io/platform/latest/operator-guides/deploy/sn-deploy) and [TIDB](https://docs.pingcap.com/tidb-in-kubernetes/v1.0/deploy-on-general-kubernetes). They install the operator first, and then install the cluster. I think we should maintain the status quo, but we need to add the dependencies in the document.
1. When using operator-cluster-charts, the documentation should explain that operator-charts needs to be installed first.
2. Maybe we need to rename operator-cluster-charts because its name is confusing.

**Comment by mlycore** [comment]
That's it, people want to play with Apache ShardingSphere on kubernetes should not get confused with the name `operator-charts` and `operator-cluster-charts`.

**Comment by mlycore** [comment]
fixed in #149
