### ISSUE TITLE
[Discussion] `Stragegy` changing for `Deployment` configuration of ShardingSphere-Proxy

### ISSUE THREAD

**Issue by xuanyuan300** [apache/shardingsphere-on-cloud#168]
## Background
Currently, in the `Deployment` configuration generated by `ShardingSphere Operator` for `ShardingSphere-Proxy`, the Strategy is `v1.RecreateDeploymentStrategyType`. This will cause the `proxy pod` to be  deleted and rebuilt when the user updates, cause a temporary interruption of the user connect to the proxy.

## Plan
The `Strategy` of the `Deployment` for `SahrdingSphere-Proxy` should be changed to `RollingUpdateDeploymentStrategyType` to avoid connetcion lost cause temporary interruption

**Comment by mlycore** [comment]
LGTM. What will be the default upgrading setup, like maxUnavailable and maxSurge?

**Comment by mlycore** [comment]
In pr #172,  it changes default `Strategy` from `Recreate` to `RollingUpdate` and only supports this kind. Parameters used in `RollingUpdate` are not proposed in CRD `ShardingSphereProxy`, because it will be deprecated in future release. 

So users could custom this `maxSurge` and `maxUnavailable` via annotations `shardingsphereproxy.shardingsphere.org/rolling-update-max-surge` and `shardingsphereproxy.shardingsphere.org/rolling-update-max-unavailable` respectively.

**Comment by mlycore** [comment]
solved in #172
